In [1]:
import numpy as np

In [3]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(X)

[[ -2.58364073   6.82920845   9.23119137 ... -11.09680818   0.32660501
   -4.35615197]
 [  1.58127133  -3.88879257  -2.8842747  ...   6.30313103   0.67348351
   10.61572929]
 [ -5.50381045 -14.45938696   4.61997502 ...  -1.81292647  -2.88508068
    6.97564003]
 ...
 [ 15.72004275 -23.81193137  13.6504634  ...  -3.83250937  -5.18185432
    7.52957611]
 [ -4.46510442   5.6966831   -3.77730648 ...  -8.29610199   4.59284303
   -3.67674564]
 [  4.93705654   9.43180503  -5.94865457 ...   4.85679698  -0.51945651
   13.54843222]]


In [4]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
print(Z)

[[4 5 0]
 [1 9 3]
 [5 1 1]
 [3 3 3]
 [9 9 9]
 [4 7 1]]


In [5]:
r = np.sum(Z, axis=1)
print (np.nonzero(r > 10))

(array([1, 4, 5]),)


In [6]:
m1 = np.eye(3)
m2 = np.eye(3)
m12 = np.vstack((m1, m2))
print(m12)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
